version: '3'
services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27020:27017
  test-mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_DB_USERNAME: test_admin
      MONGO_DB_PASSWORD: test_admin
      MONGODB_DATABASE: test-db
    ports:
      - 27021:27017
